[project]
name = "10-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-ai>=0.7.2",
    "streamlit>=1.48.1",
]
